#ifndef CONSTANTS_VERSION_H
#define CONSTANTS_VERSION_H

#define CONSTANTS_VERSION_MAJOR 1
#define CONSTANTS_VERSION_MINOR 0
#define CONSTANTS_VERSION_PATCH 0

#define CONSTANTS_VERSION (CONSTANTS_VERSION_MAJOR * 10000 + CONSTANTS_VERSION_MINOR * 100 + CONSTANTS_VERSION_PATCH)

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#define CONSTANTS_VERSION_STRING STRINGIFY(CONSTANTS_VERSION_MAJOR) "." STRINGIFY(CONSTANTS_VERSION_MINOR) "." STRINGIFY(CONSTANTS_VERSION_PATCH)

namespace CONSTANTS
{
    inline constexpr int version_major = CONSTANTS_VERSION_MAJOR;
    inline constexpr int version_minor = CONSTANTS_VERSION_MINOR;
    inline constexpr int version_patch = CONSTANTS_VERSION_PATCH;
    inline constexpr int version = CONSTANTS_VERSION;
    inline constexpr const char *version_string = CONSTANTS_VERSION_STRING;
}

#endif
